steps:
  # This step builds the container image.
  - id: "Build e2e docker image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/e2e", "."]

  # This step pushes the image to Container Registry
  # The PROJECT_ID variables are automatically
  # replaced by Cloud Build.
  - name: "gcr.io/cloud-builders/docker"
    id: "Push docker image to container registry"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/e2e"

  # This step creates a GKE cluster
  # with 1 node
  # config of 8 cpu and 32gb ram.
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Create GKE cluster"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud container clusters create $_CUSTOM_CLUSTER --num-nodes=1 --machine-type=e2-standard-8

    env:
      - CLOUDSDK_COMPUTE_ZONE=$_CUSTOM_ZONE

  # This step deploys selenosis setup
  # in the Kubernetes Engine cluster.
  - name: "gcr.io/cloud-builders/gke-deploy"
    id: "Deploy selenosis setup"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud container clusters get-credentials $_CUSTOM_CLUSTER
        sh ./selenosis-deploy/script.sh
    env:
      - CLOUDSDK_COMPUTE_ZONE=$_CUSTOM_ZONE

  # This step deploys e2e tests
  # in the Kubernetes Engine cluster.
  - name: "gcr.io/cloud-builders/gke-deploy"
    id: "Deploy e2e"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud container clusters get-credentials $_CUSTOM_CLUSTER
        kubectl apply -f e2e-test.yml
    env:
      - CLOUDSDK_COMPUTE_ZONE=$_CUSTOM_ZONE

substitutions:
  _CUSTOM_ZONE: asia-south1-a
  _CUSTOM_CLUSTER: gke-cluster
