steps:
  # This step builds the container image.
  - id: "Build e2e docker image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/e2e", "."]

  # This step pushes the image to Container Registry
  # The PROJECT_ID and SHORT_SHA variables are automatically
  # replaced by Cloud Build.
  - name: "gcr.io/cloud-builders/docker"
    id: "Push docker image to container registry"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/e2e"

  # This step deploys the new version of our container image
  # in the Kubernetes Engine cluster.
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Create GKE cluster"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud container clusters create $_CUSTOM_REGION --num-nodes=6 --machine-type=custom-8-12288

    env:
      - CLOUDSDK_COMPUTE_REGION=$_CUSTOM_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CUSTOM_CLUSTER

  # This step deploys the new version of our container image
  # in the Kubernetes Engine cluster.
  - name: "gcr.io/cloud-builders/gke-deploy"
    id: "Deploy selenosis setup"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud container clusters get-credentials $_CUSTOM_REGION --region=$_CUSTOM_REGION
        sh ./selenosis-deploy/script.sh
    env:
      - CLOUDSDK_COMPUTE_REGION=$_CUSTOM_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CUSTOM_CLUSTER

  - name: "gcr.io/cloud-builders/kubectl"
    id: "Deploy e2e"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud container clusters get-credentials $_CUSTOM_REGION --region=$_CUSTOM_REGION
        kubectl apply -f e2e-test.yml
    env:
      - CLOUDSDK_COMPUTE_REGION=$_CUSTOM_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CUSTOM_CLUSTER

substitutions:
  _CUSTOM_REGION: us-central1
  _CUSTOM_CLUSTER: gke-cluster
