steps:
  # This step builds the container image.
  - id: "Build e2e docker image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/e2e:$SHORT_SHA", "."]

  # This step pushes the image to Container Registry
  # The PROJECT_ID and SHORT_SHA variables are automatically
  # replaced by Cloud Build.
  - name: "gcr.io/cloud-builders/docker"
    id: "Push docker image to container registry"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/e2e:$SHORT_SHA"

  # This step deploys the new version of our container image
  # in the Kubernetes Engine cluster.
  - name: "gcr.io/cloud-builders/kubectl"
    id: "Deploy selenosis setup"
    entrypoint: "bash"
    args:
      - "sh ./selenosis-deploy/script.sh"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-b"

  - name: "gcr.io/cloud-builders/kubectl"
    id: "Deploy e2e"
    args: ["apply", "-f", "e2e-test.yml"]
