apiVersion: batch/v1
kind: Job
metadata:
  name: e2e
  namespace: selenosis
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        selenosis.app.type: worker
    spec:
      containers:
        - name: e2e
          imagePullPolicy: IfNotPresent
          image: gcr.io/wdio-gke/e2e:latest
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      terminationGracePeriodSeconds: 0
